CREATE_USERS_TABLE = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    salt TEXT NOT NULL,
    password_hash TEXT NOT NULL
);
"""

CREATE_STOCK_CACHE_TABLE = """
CREATE TABLE IF NOT EXISTS stock_cache (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    date TEXT NOT NULL,
    price REAL NOT NULL,
    returns REAL NOT NULL,
    volume INTEGER NOT NULL,
    trend TEXT NOT NULL,
    UNIQUE(symbol, date)
)
"""